pinkoproj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from sumkiapp import views as sumkiapp_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sumkiapp.urls')),
]


handler404 = sumkiapp_views.error_404
handler500 = sumkiapp_views.error_500

sumkiapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from .sitemaps import ProductSitemap, StaticViewSitemap, CollectionSitemap


app_name = "sumkiapp"

sitemaps = {
    'products': ProductSitemap,
    'static': StaticViewSitemap,
    'collect': CollectionSitemap,
} 

urlpatterns = [
    path('auth/', views.auth, name='auth'),
    path('review_add', views.review_add, name='review_add'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path('robots.txt', TemplateView.as_view(template_name='sumkiapp/robots.txt', content_type='text/plain')),
    path('', views.homepage, name='homepage'),
    path('catalog/', views.homepage, name='homepage'),
    path('favorites/', views.favorites, name='favorites'),
    path('addfav/<id>', views.add_to_fav, name='add_to_fav'),
    path('removefav/<id>', views.remove_from_fav, name='remove_from_fav'),
    path('product/<ide>/', views.product_view, name='product_view'),
    path('search/', views.search, name='search'),
    path('terms-of-use/', views.terms_of_use, name="terms_of_use"),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('create/', views.order_create, name='order_create'),
    path('products/', views.homepage, name='homepage'),
    path('cart/', views.cart_detail, name='cart_detail'),
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove'),
    path('delivery/', views.delivery, name='delivery'),
    path('Backpacks/', views.backpacks, name='backpacks'),
    path('about/', views.about, name='about'),
    path('reviews/', views.reviews, name='reviews'),
    path('contacts/', views.contacts, name='contacts'),
    path('fast_order/', views.new_quickorder, name='fast_order'),
    path("<coll_name>/", views.collection, name='collection'),


    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sumkiapp/models.py
from django.db import models
import datetime




class Product(models.Model):
    product_name = models.CharField(max_length=200)
    old_price = models.CharField(max_length=20, blank=True, null=True)
    price = models.CharField(max_length=20)
    article = models.CharField(max_length=50)
    descrip = models.TextField()
    descripoint = models.TextField(blank=True, null=True)
    images = models.ManyToManyField('ProductImage', related_name='products', blank=True, null=True)
    category = models.ManyToManyField('ProductCategory', related_name='products')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Products"
        ordering = ['id']

    def __str__(self):
        return self.product_name

    def get_absolute_url(self):
        name = '/product/' + str(self.pk) + '/'
        return name


class ProductImage(models.Model):
    image = models.ImageField(upload_to='images', blank=True, null=True)



class ProductCategory(models.Model):
    product_category = models.CharField(max_length=20)

    def __str__(self):
        return self.product_category

class Quickorder(models.Model):
    product_name = models.CharField(max_length=200)
    name = models.CharField(max_length=100, blank=True, null=True)
    phone = models.CharField(max_length=100)
    address = models.CharField(max_length=200, blank=True, null=True)
    comment = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

class Order(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=50)
    email = models.CharField(max_length=50,blank=True, null=True)
    city = models.CharField(max_length=100, default='Москва',blank=True, null=True)
    address = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    comment = models.CharField(max_length=200, blank=True, null=True)


    class Meta:
        ordering = ('-created',)
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def __str__(self):
        return 'Заказ {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity


class Review(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    comment = models.TextField()
    image = models.ImageField(upload_to='images', blank=True, null=True)
    moderated = models.BooleanField(default=False)

sumkiapp/forms.py
from django import forms
from .models import Order


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class Quickorderform(forms.Form):
    product_name = forms.CharField(max_length=200)
    name = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваше имя'}))
    phone = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваш телефон'}))
    address = forms.CharField(max_length=200, required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваш город'}))
    comment = forms.CharField(max_length=200, required=False, widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'При желании, вы можете оставить комментарий к заказу','size': '20'}))

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label="Кол-во ")
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['name','phone','address','comment','city','email']

class Searchform(forms.Form):
    searched = forms.CharField(max_length=100, label="")

class Reviewform(forms.Form):
    name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваше имя'}))
    email = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваш e-mail'}))
    comment = forms.CharField(max_length=1000, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ваш отзыв'}))
    image = forms.ImageField(required=False)

sumkiapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST, require_GET
from .cart import *
from .models import *
from .forms import Quickorderform, CartAddProductForm, OrderCreateForm, Searchform, Reviewform
from django.core.paginator import Paginator
from django.http import Http404, HttpResponse
from django.conf import settings
from django.contrib.staticfiles import finders
from .obj_create import create_order, save_quickorder, create_review
from .email_logic import moscowtime, logo_data, mail_validation, send_quickorder_email, send_order_email, order_create_and_send, quickorder_create_and_send


def auth(request):
    return render(request, 'sumkiapp/auth.html')

def product_view(request, ide):
    this_product = Product.objects.get(id = ide)
    form = Quickorderform(initial={'product_name': this_product.id})
    form2 = CartAddProductForm()
    return render(request, 'sumkiapp/product_page.html', {"product": this_product, 'form':form, 'form2':form2})

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order_create_and_send(form,cart)
            cart.clear()
            return render(request, 'sumkiapp/created.html')
    else:
        form = OrderCreateForm
    return render(request, 'sumkiapp/create.html', {'cart': cart, 'form': form})

def is_ajax(request):
    return request.META.get("HTTP_X_REQUESTED_WITH") == "XMLHttpRequest"

@require_GET
def homepage(request):
    products_all = Product.objects.all()
    paginator = Paginator(products_all, per_page=8)
    page_num = int(request.GET.get("page", 1))
    if page_num > paginator.num_pages:
        return HttpResponse(status=200)
    products = paginator.page(page_num)
    context = {'products': products}
    if is_ajax(request):
        return render(request, 'sumkiapp/_products.html', {'products': products})
    return render(request, 'sumkiapp/homepage.html', context)

def delivery(request):
    return render(request, 'sumkiapp/delivery.html')

def backpacks(request):
    backpacks = Product.objects.filter(product_category__contains= "Backpack")
    return render(request, 'sumkiapp/backpacks.html', context = {"products": backpacks})

def about(request):
    return render(request, 'sumkiapp/about.html')

def reviews(request):
    mod_reviews = Review.objects.filter(moderated=True)
    form = Reviewform()
    return render(request, 'sumkiapp/reviews.html', {'form':form, 'reviews': mod_reviews})

def contacts(request):
    return render(request, 'sumkiapp/contacts.html')

def collection(request, coll_name):
    collections = ProductCategory.objects.values_list('product_category', flat = True)
    if coll_name in collections:
        content = Product.objects.filter(category__product_category__contains=coll_name).distinct()

        return render(request, 'sumkiapp/collection.html', {"products": content, "coll": coll_name})
    
    return render(request, "sumkiapp/404page.html", status=404) 

def new_quickorder(request):
    if request.method == 'POST':
        form = Quickorderform(request.POST)
        if form.is_valid():
            quickorder_create_and_send(form)
            return redirect('/')

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('sumkiapp:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('sumkiapp:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'sumkiapp/detail.html', {'cart': cart})

def terms_of_use(request):
    return render(request, 'sumkiapp/terms_of_use.html')

def privacy_policy(request):
    return render(request, 'sumkiapp/privacy_policy.html')

def error_404(request, exception):
    return render(request, "sumkiapp/404page.html", status=404)


def error_500(request):
    return render(request, 'sumkiapp/500page.html', status=500)

@require_POST
def search(request):
    form = Searchform(request.POST)
    if form.is_valid():
        searchword = form.cleaned_data['searched']
        content = Product.objects.filter(product_name__contains=searchword)
        return render(request, 'sumkiapp/searched.html', {"products": content, "searchword": searchword})


def add_to_fav(request, id):
    if request.method == 'POST':
        if not request.session.get('favorites'):
            request.session['favorites'] = list()
        else:
            request.session['favorites'] = list(request.session['favorites'])

        item_exists = next((item for item in request.session['favorites'] if item['type'] == request.POST.get('type') and item['id'] == id), False)

        add_data = {
            'type': request.POST.get('type'),
            'id': id,
        }

        if not item_exists:
            request.session['favorites'].append(add_data)
            request.session.modified = True
    return redirect(request.POST.get('url_from'))


def remove_from_fav(request, id):
    if request.method == 'POST':

        for item in request.session['favorites']:
            if item['id'] == id and item['type'] == request.POST.get('type'):
                item.clear()

        while {} in request.session['favorites']:
            request.session['favorites'].remove({})

        if not request.session['favorites']:
            del request.session['favorites']

        request.session.modified = True
    return redirect(request.POST.get('url_from'))

def favorites(request):
    favs = []
    if not request.session.get('favorites'):
        request.session['favorites'] = list()

        fav_products = []

    else:
        for item in request.session['favorites']:
            favs.append(item['id'])
            fav_products = Product.objects.filter(pk__in=favs)
    
    return render(request, 'sumkiapp/favs.html', {"products": fav_products})

def catalog(request):
    products = Product.objects.all().order_by('id')[:8]
    return render(request, 'sumkiapp/catalog.html', {"products": products})

def review_add(request):
    if request.method == 'POST':
        form = Reviewform(request.POST, request.FILES)
        if form.is_valid():
            create_review(form)
            return redirect('/')

sumkiapp/templates/sumkiapp/500page.html
{% extends 'sumkiapp/header.html' %}
{% load static %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
<h2 align="center">ЧТО ТО ПОШЛО НЕ ТАК, ПОВТОРИТЕ ПОЗДНЕЕ</h2>
<br>
<br>
<br>
	<div class="center">
      <a href="/">
        <button class="btn btn-outline-dark" type="button">НА ГЛАВНУЮ
        </button>
      </a>
     </div>
<br>
<br>
{% endblock %}

sumkiapp/templates/sumkiapp/_product.html
<div class="col-xs-1 col-sm-3 col-lg-3 col-md-3" align="center">
        <a href="/product/{{ product.id }}">
        <div class="zoom">
        <img src="{{ product.images.first.image.url}}" class="img-fluid">
        </div>
        </a>
        <a href="/product/{{ product.id }}" >{{ product.product_name }}</a>
        <br>
        <p>{% if not product.old_price %}{% else %}<s>{{ product.old_price }}</s> руб  {% endif %}<strong>{{ product.price }} руб</strong></p>
      </div>

sumkiapp/templates/sumkiapp/_products.html
		{% for product in products %}
		{% include "sumkiapp/_product.html" with product=product %}
		{% endfor %}

sumkiapp/templates/sumkiapp/about.html
{% extends 'sumkiapp/header.html' %}

{% block content %}
<br>
<br>
<br>
<br>
<br>
<div class="container">
	<p>"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."</p>


</div>
{% endblock %}

sumkiapp/templates/sumkiapp/auth.html
{% extends 'sumkiapp/header.html' %}

{% block content %}
<br>
<br>
<br>
<div class="container">
<h1>Sed ut perspiciatis </h1>
<p>"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"</p>

</div>
{% endblock %}

sumkiapp/templates/sumkiapp/collection.html
{% extends 'sumkiapp/header.html' %}


{% block content %}
	<h1 align="center">СУМКИ  {{ coll }}</h1>
	<div class="container-fluid">
	<div class="row">
		{% for product in products %}
			<div class="col-xs-1 col-sm-3 col-lg-3 col-md-3" align="center">
				<a href="{{ product.get_absolute_url }}">
				<div class="zoom">
				<img src="{{ product.images.first.image.url }}" class="img-fluid">
				</div>
				</a>
				<a href="{{ product.get_absolute_url }}">{{ product.product_name }}</a>
				<br>
				<p><s>{{ product.old_price }}</s> руб  <strong>{{ product.price }} руб</strong></p>
			</div>
		{% endfor %}
	</div>
	</div>

{% endblock %}

sumkiapp/templates/sumkiapp/contacts.html
{% extends 'sumkiapp/header.html' %}

{% block content %}
<br>
<br>
<br>
<br>
<div class="container">
<h1>Lorem Ipsum</h1>
<p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
{% endblock %}

sumkiapp/templates/sumkiapp/created.html
 {% extends 'sumkiapp/header.html' %}
{% load static %}

{% block content %}
<br>
<br>
<br>
<br>
<br>
    <h1>СПАСИБО</h1>
    <p>ВАШ ЗАКАЗ БЫЛ УСПЕШНО СОЗДАН.</p>
{% endblock %}

sumkiapp/templates/sumkiapp/delivery.html
{% extends 'sumkiapp/header.html' %}
{% load static %}

{% block content %}
<br>
<br>
<br>
<br>
<div class="container">
<p>"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."</p>
</div>
{% endblock %}

sumkiapp/templates/sumkiapp/favs.html
{% extends 'sumkiapp/header.html' %}


{% block content %}
<br>
<br>
<br>
<br>

	<h1 align="center">ИЗБРАННЫЕ ТОВАРЫ</h1>
	<div class="container-fluid">
	<div class="row">
		{% for product in products %}
			<div class="col-xs-1 col-sm-3 col-lg-3 col-md-3">
				<a href="{{ product.get_absolute_url }}">
				<div class="zoom">
				<img src="{{ product.primary_image.url }}" class="img-fluid">
				</div>
				</a>
				<a href="{{ product.get_absolute_url }}">{{ product.product_name }}</a>
				<br>
				<p style="float: left;"><s>{{ product.old_price }}</s> руб  <strong>{{ product.price }} руб</strong></p>
			</div>
		{% endfor %}
	</div>
	</div>
{% endblock %}

sumkiapp/templates/sumkiapp/header.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<!-- CSS only -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

  <title>{% block title %}{% endblock %}</title>

	<meta name='viewport' content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1">

  <meta name="description" content="{% block description %}{% endblock %}">
 
  <link rel="shortcut icon" type="image/jpg" href="{% static 'sumkiapp/fav12.png' %}">
  
  <link rel="stylesheet" type="text/css" href="{% static 'sumkiapp/css/styling.css' %}">



    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>



</head>

<body>
	<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-white">
  <div class="container-fluid">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


    <a href="/">
  	<img  width="220" height="60"src="{% static 'sumkiapp/123.jpg' %}">
    </a>


      <ul class="nav navbar-nav d-md-none">
      <li class="pull-left"><a href="{% url 'sumkiapp:cart_detail' %}"><img class="resize"  src="{% static 'sumkiapp/shopping-cart.png' %}"></a></li>
    </ul>

          <ul class="nav navbar-nav d-md-none">
      <li class="pull-left"><a href="{% url 'sumkiapp:favorites' %}"><img class="resize"  src="{% static 'sumkiapp/heart.png' %}"></a></li>
    </ul>




    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 mx-auto">
        <li class="nav-item">
          <a class="nav-link" href="/catalog" style="font-size:14px;"><strong>ГЛАВНАЯ</strong></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" data-toggle='dropdown' aria-expanded="false" style="font-size:14px;"><strong>
            КОЛЛЕКЦИИ
          </strong></a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

            {% for i in header_categories %}
                <li><a class="dropdown-item" href="/{{ i }}">{{ i }}</a></li>
            {% endfor %}
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/auth" style="font-size:14px;"><strong>АУТЕНТИЧНОСТЬ</strong></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/delivery" style="font-size:14px;"><strong>ДОСТАВКА</strong></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/about" style="font-size:14px;"><strong>О НАС</strong></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/reviews" style="font-size:14px;"><strong>ОТЗЫВЫ</strong></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/contacts" style="font-size:14px;"><strong>КОНТАКТЫ</strong></a>
        </li>
      </ul>

      <form class="d-flex" action="{% url 'sumkiapp:search' %}" method="post">
        {% csrf_token %}
        {{ search_form }}
        <button class="btn btn-outline-dark" type="submit" style="margin-bottom: 4px;">
          <img class='resize'src="{% static 'sumkiapp/search.png' %}">
        </button>
      </form>

      <div class='d-flex d-none d-lg-block' style="margin-bottom: 4px;margin-left: 3px; float: left;">
      <a href="{% url 'sumkiapp:cart_detail' %}" style="margin-left: 1px;margin-top: 5px;">
        <button class="btn btn-outline-dark" type="button">
          <img class='resize' src="{% static 'sumkiapp/shopping-cart.png' %}">
        </button>
      </a>
    </div>

      <div class='d-flex d-none d-lg-block' style="margin-bottom: 5px;margin-left: 3px;">
      <a href="{% url 'sumkiapp:favorites' %}" style="margin-left: 1px;margin-top: 5px;">
        <button class="btn btn-outline-dark" type="button">
          <img class='resize' src="{% static 'sumkiapp/heart.png' %}">
        </button>
      </a>
    </div>



    </div>
</nav>
{% block content %}
{% endblock %}
<br>
<br>

<footer>
<p style="font-size:13px; line-height:1.5;">Sample logo / Интернет-магазин  / <strong><a href="/privacy-policy">Политика конфиденциальнсти</a></strong> и <strong><a href="/terms-of-use">пользовательское соглашение</a></strong></p>
</footer>
</body>
</html>

sumkiapp/templates/sumkiapp/privacy_policy.html
{% extends 'sumkiapp/header.html' %}
{% load static %}
{% block content %}
<br>
<br>
<h3 align="center">ПОЛИТИКА КОНФИДЕНЦИАЛЬНОСТИ</h3>
<br>
<div class="container">

</div>

{% endblock %}

sumkiapp/templates/sumkiapp/quick_email_template.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title></title>
</head>
<body>
	       <div class="center">
			<h2 style="background-color: grey; text-align: left;">Время: {{ time }}  Номер заказа: Б{{ iden }}</h2>
        </div>


<p>Телефон: {{ phone }}</p>
<p>Город: {{ address }}</p>
<p>Коммент: {{ comment }}</p>


<table class="table table-hover table-responsive">

<thead>
    <tr>
        <th></th>
        <th>ТОВАР</th>
        <th>ЦЕНА</th>
    </tr>
</thead>

<tbody>
    <tr>
	    <td>
         <a href="https://www.yourdomain.com/{{ product.get_absolute_url }}">
          <img src="cid:{{ product.pk }}" width="150" height="150">
         </a>
        </td>
        <a href="https://www.yourdomain.com/{{ product.get_absolute_url }}">
        <td>{{ product.product_name}}</td>
        </a>
        <td>{{ product.article }}</td>
        <td>{{ product.price }}</td>
    </tr>
</tbody>

</table>

</body>
</html>